services:
  - docker

git:
  depth: 1

env:
  global:
    - COMMIT="${TRAVIS_COMMIT::8}"
    - REPO=afsmnghr/wifite

before_install:
  - wget https://github.com/knqyf263/trivy/releases/download/v0.0.13/trivy_0.0.13_Linux-64bit.tar.gz
  - tar zxvf trivy_0.0.13_Linux-64bit.tar.gz

script:
  - docker build -t "${TRAVIS_BUILD_NUMBER}" -f Dockerfile $(pwd)
  - ./trivy --exit-code 0 --severity HIGH --quiet "${TRAVIS_BUILD_NUMBER}"
  - ./trivy --exit-code 1 --severity CRITICAL --quiet "${TRAVIS_BUILD_NUMBER}"
  - docker run --rm -t "${TRAVIS_BUILD_NUMBER}" wifite -h

after_success:
  - export $(cat .env)
  - export ID=`docker run --rm -dt "$TRAVIS_BUILD_NUMBER" sh`
  - docker export "$ID" | docker import - "$REPO:$VERSION"
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker tag "$REPO:$VERSION" "$REPO:$COMMIT"
  - docker tag "$REPO:$VERSION" "$REPO:latest"
  - docker push "$REPO"

cache:
  directories:
    - $HOME/.cache/trivy
