services:
  - docker

git:
  depth: 1

env:
  global:
    - COMMIT="${TRAVIS_COMMIT::8}"
    - REPO=afsmnghr/wifite

# before_install:
  # - wget https://github.com/aquasecurity/trivy/releases/download/v0.1.7/trivy_0.1.7_Linux-64bit.tar.gz
  # - tar zxvf trivy_0.1.7_Linux-64bit.tar.gz

script:
  - docker build -t "$REPO:${TRAVIS_BUILD_NUMBER}" -f Dockerfile $(pwd)
  # - ./trivy --exit-code 0 --severity HIGH --no-progress --auto-refresh "$REPO:${TRAVIS_BUILD_NUMBER}"
  # - ./trivy --exit-code 1 --severity CRITICAL --no-progress --auto-refresh "$REPO:${TRAVIS_BUILD_NUMBER}"
  - docker run --rm -t "$REPO:${TRAVIS_BUILD_NUMBER}" wifite -h

after_success:
  - export $(cat .env)
  - export ID=`docker run --rm -dt "$REPO:$TRAVIS_BUILD_NUMBER" sh`
  - docker export "$ID" | docker import - "$REPO:$VERSION"
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker tag "$REPO:$VERSION" "$REPO:$COMMIT"
  - docker tag "$REPO:$VERSION" "$REPO:latest"
  - docker push "$REPO"

cache:
  directories:
    - $HOME/.cache/trivy
